### PR TITLE
Revert "Program to Check Vowel or consonant"

### PR DESCRIPTION
**Pull request by harshh351998**
Reverts professorharsh007/Hacktoberfest2020#1

### CODE REVIEW

**Comment by harshh351998** [comment]
Hmm

**Review by harshh351998 — COMMENTED** [review]
okay

**Review by professorharsh007 — APPROVED** [review]
!!

**Review by professorharsh007 — APPROVED** [review]
completed

**Review by professorharsh007 — APPROVED** [review]

**Review by harshh351998 — COMMENTED** [review]
got

**Review by professorharsh007 — APPROVED** [review]

**Review by professorharsh007 — COMMENTED** [review]
file is deleted

**Pull request merged**
